### ISSUE TITLE
trigger animation

### ISSUE THREAD

**Issue by dhonig-weizmann** [YeLwinOo-Steve/pretty_animated_text#2]
Awesome plugin!

How to re-trigger an animation? for example when pressing a "refresh" button?

**Comment by YeLwinOo-Steve** [comment]
That feature is under implementation @dhonig-weizmann . It'll be out soon

**Comment by dhonig-weizmann** [comment]
great to hear, looking forward to it 🙏

**Comment by YeLwinOo-Steve** [comment]
@dhonig-weizmann version 2 is out now and it contains custom animation controls and some major code updates. Please check https://pretty-animated-text.vercel.app/.

**Comment by dhonig-weizmann** [comment]
So cool, thank you!
